# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
 <div class="player">
       <div class="track-info">
         <h1>Song Name</h1>
         <h2>Artist Name</h2>
       </div>
       <div class="controls">
         <a href="javascript:play()">Play</a>
         <a href="javascript:pause()">Pause</a>
       </div>
    </div>

  </body>
</html>

Answer:

<!DOCTYPE html>
<html>
  <head>
    <title>Music Player Widget</title>
    <link rel="stylesheet" href="style.css" type="text/css" />
    <script src="script.js" type="text/javascript"></script>
  </head>
  <body>

    <div class="player">
       <div class="track-info">
         <h1>Song Name</h1>
         <h2>Artist Name</h2>
       </div>
       <div class="controls">
         <a href="javascript:play();">
    <h1>Music Player</h1>
    <div class="container">
      <div class="player-container">
        <iframe src="https://open.spotify.com/embed/track/24PFniyfMOMp9PsQNvznxF" width="300" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        <iframe src="https://open.spotify.com/embed/track/6kmkGUerc7QytLzAulVYV6" width="300" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
      </div>
    </div>
  </body>
</html>
